name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.17

      - name: Build Linux
        run: GOARCH=arm64 GOOS=linux go build -ldflags "-s -w -extldflags" -o solid-gaucamole-linux .

      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: binaries
          path: solid-gaucamole-linux
